[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
  milesburton/DallasTemperature
  bblanchon/ArduinoJson
  paulstoffregen/OneWire
  adafruit/Adafruit MPU6050
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO

upload_speed = 115200